version: '3.7'

services:
  privoxy:
    container_name: privoxy
    image: vimagick/privoxy

    ports:
      - "8118:8118"

    volumes:
      - $PWD/privoxy/user.action:/etc/privoxy/user.action:ro

    cap_add:
      - NET_ADMIN

    restart: always
